// A list of student codewars profile URLs
// the output will be in the order of the array

module.exports = [
  'https://www.codewars.com/users/mic80205',
  'https://www.codewars.com/users/Rosebud303',
  'https://www.codewars.com/users/JustKamina',
  'https://www.codewars.com/users/rdren0',
  'https://www.codewars.com/users/raechelo',
  'https://www.codewars.com/users/SallyHaefling',
  'https://www.codewars.com/users/JellyBeans1312',
  'https://www.codewars.com/users/B-Coyle',
  'https://www.codewars.com/users/colbyallen012',
  'https://www.codewars.com/users/BrennanDuffey',
  'https://www.codewars.com/users/KirbyDD',
  'https://www.codewars.com/users/emilydittmer',
  'https://www.codewars.com/users/ehk9000',
  'https://www.codewars.com/users/alizarincrimson',
  'https://www.codewars.com/users/jacobogart',
  'https://www.codewars.com/users/jacquelinebelle',
  'https://www.codewars.com/users/jarrettkong',
  'https://www.codewars.com/users/joejohnson3985',
  'https://www.codewars.com/users/kalex19',
  'https://www.codewars.com/users/KaylaRae',
  'https://www.codewars.com/users/misskelly',
  'https://www.codewars.com/users/KevinKra',
  'https://www.codewars.com/users/lboyer4',
  'https://www.codewars.com/users/lynnerang',
  'https://www.codewars.com/users/kobesparrow',
  'https://www.codewars.com/users/Matthew%20Kaplan',
  'https://www.codewars.com/users/MaxBSilver',
  'https://www.codewars.com/users/NimSum',
  'https://www.codewars.com/users/RyanDBarnett',
  'https://www.codewars.com/users/saadricklamar',
  'https://www.codewars.com/users/tiffanybacher'
];
